apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: backstage
commonLabels:
  type: app
resources:
- ./postgres
- ./backstage.yaml
- ./backstage-sa.yaml
generators:
- ./secret-generator.yaml
images:
- name: 160071257600.dkr.ecr.ap-northeast-1.amazonaws.com/backstage
  newName: 160071257600.dkr.ecr.ap-northeast-1.amazonaws.com/backstage
  newTag: master-69051-1688522042-6
