apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: backstage
commonLabels:
  type: app
resources:
  - ./postgres
  - ./backstage.yaml
generators:
  - ./secret-generator.yaml